apiVersion: v1
kind: Service
metadata:
  name: nest-erp
  namespace: mp
  labels:
    pod: nest
spec:
  type: NodePort
  ports:
    - name: tcp
      protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 13050
    - name: grpc
      protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 13051
  selector:
    pod: nest-erp
