apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eventstoredb
  namespace: mp
  labels:
    pod: eventstoredb
spec:
  selector:
    matchLabels:
      pod: eventstoredb
  serviceName: eventstoredb
  replicas: 1
  template:
    metadata:
      labels:
        pod: eventstoredb
    spec:
      securityContext:
        fsGroup: 1000 # Обновите в соответствии с вашим окружением
      containers:
        - name: eventstoredb
          image: eventstore/eventstore:24.2.0-jammy
          ports:
            - containerPort: 2113 # HTTP интерфейс
            - containerPort: 1113 # TCP интерфейс
          env:
            - name: EVENTSTORE_CLUSTER_SIZE
              value: "1"
            - name: EVENTSTORE_RUN_PROJECTIONS
              value: "All"
            - name: EVENTSTORE_START_STANDARD_PROJECTIONS
              value: "true"
            - name: EVENTSTORE_HTTP_PORT
              value: "2113"
            - name: EVENTSTORE_INSECURE
              value: "true"
            - name: EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP
              value: "true"

          volumeMounts:
            - mountPath: /var/lib/eventstore
              name: eventstoredata
            - mountPath: /var/log/eventstore
              name: eventstorelog

      #          command: [ "/bin/bash", "-c", "--" ]
      #          args: [ "while true; do sleep 30; done;" ]
      volumes:
        - name: eventstoredata
          hostPath:
            path: "/mnt/ssd_mirror_1000/apps/metricsplace/erp/eventstore/data"
        - name: eventstorelog
          hostPath:
            path: "/mnt/ssd_mirror_1000/apps/metricsplace/erp/eventstore/log"
