

type User {
  id: Int!
}

type Query {
  accessToken: String! # это хранится в кеше

  signOut: Boolean
  userData: User!
}

input SignUp {
  username: String!
  email: String!
  password: String!
  passwordConfirm: String!
}

type SignUpResponse {
  success: Boolean!
}

input SignIn {
  email: String!
  password: String!
}

type RefreshTokenResponse {
  accessToken: String
}
type SignInResponse {
  accessToken: String
}

type Mutation {
  signUp(input: SignUp!): SignUpResponse!
  signIn(input: SignIn!): SignInResponse!
  signOut: Boolean
  refreshToken: RefreshTokenResponse!
}

