kind: PersistentVolume
apiVersion: v1
metadata:
  name: redis
  labels:
    pod: redis
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/hdd_mirror/apps/metricsplace/base/redis"
