apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: mp
  labels:
    pod: redis
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: redis
  resources:
    requests:
      storage: 10Gi