apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: mp
  labels:
    pod: redis
spec:
  type: NodePort
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 9381
  selector:
    pod: redis