apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: mp
  labels:
    pod: redis
spec:
  selector:
    matchLabels:
      pod: redis
  serviceName: redis
  replicas: 1
  template:
    metadata:
      labels:
        pod: redis
    spec:
      containers:
        - name: redis-server
          image: redis
          args: ["--appendonly", "yes"]
          ports:
            - name: redis-server
              containerPort: 6379
          volumeMounts:
            - name: lv-storage
              mountPath: /data
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      volumes:
        - name: lv-storage
          persistentVolumeClaim:
            claimName: redis